server:
  port: 8889

spring:
  application:
    name: Config-Service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AkshayaPk/config-microservices.git
            #default-label: localTestBranch
          
